version: '3.9'

services:

  db:
    image: postgres:13
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - internal_network

  django:
    build: ./lycaste
    volumes:
      - ./data/img:/app/main/static/img
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=db
    depends_on:
      - db
    networks:
      - internal_network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # for website config
      - /etc/letsencrypt:/etc/letsencrypt         # for ssl keys
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - django
    networks:
      - internal_network

  smtp:
    image: tvial/docker-mailserver:latest
    hostname: mail
    domainname: lycaste.eu
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ./data/smtp/postfix:/usr/lib/postfix
      - ./data/smtp/dovecot:/etc/dovecot
    ports:
      - "25:25"    # SMTP
      - "143:143"  # IMAP
      - "465:465"  # SMTPS
      - "587:587"  # Submission
      - "993:993"  # IMAPS
    environment:
      - SSL_TYPE=manual
      - SSL_CERT_PATH=/etc/letsencrypt/live/lycaste.eu/fullchain.pem
      - SSL_KEY_PATH=/etc/letsencrypt/live/lycaste.eu/privkey.pem
      - ENABLE_SPAMASSASSIN=1
      - ENABLE_CLAMAV=1
      - ENABLE_FAIL2BAN=1

networks:
  internal_network:
      driver: bridge