version: '3.9'

services:

  db_dev:
    image: postgres:13
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    networks:
      - internal_network

  django_dev:
    build: ./lycaste
    restart: always
    volumes:
      - ./data/img:/app/main/static/img
      - ./data/migrations/main:/app/main/migrations
      - ./data/migrations/authentication:/app/authentication/migrations
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=db_dev
      - POSTGRES_PORT=5432
    depends_on:
      - db_dev
    networks:
      - internal_network
      
networks:
  internal_network:
      driver: bridge