version: '3.9'

services:

  db:
    image: postgres:13
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT_MAPPING}
    networks:
      - internal_network

  django:
    build: ./lycaste
    volumes:
      - ./data/img:/app/main/static/img
      - ./data/migrations/main:/app/main/migrations
      - ./data/migrations/authentication:/app/authentication/migrations
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=db
    depends_on:
      - db
    networks:
      - internal_network

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./data/certbot/www/:/var/www/certbot/:rw
      - ./data/certbot/conf/:/etc/letsencrypt/:rw
    deploy:
      replicas: ${PROD_REPLICAS}

  wordpressdb:
    image: mysql:5.
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: wp
    volumes:
      - ./data/wordpress/db:/var/lib/mysql
    networks:
      - internal_network
    deploy:
      replicas: ${PROD_REPLICAS}

  wordpress:
    image: wordpress:latest
    environment:
      WORDPRESS_DB_HOST: wordpressdb:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: ""
      WORDPRESS_DB_NAME: wp
    volumes:
      - ./data/wordpress/content:/var/www/html/wp-content
    depends_on:
      - wordpressdb
    networks:
      - internal_network
    deploy:
      replicas: ${PROD_REPLICAS}

  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:14.0.0
    hostname: mail.lycaste.eu
    ports:
      - "25:25"     # SMTP
      - "465:465"   # SMTPS (SSL)
      - "587:587"   # Submission (STARTTLS)
      - "993:993"   # IMAPS (SSL)
    volumes:
      - ./data/mailserver/mail-data/:/var/mail/
      - ./data/mailserver/mail-state/:/var/mail-state/
      - ./data/mailserver/mail-logs/:/var/log/mail/
      - ./data/mailserver/config/:/tmp/docker-mailserver/
      - /etc/letsencrypt/:/etc/letsencrypt:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - ENABLE_SPAMASSASSIN=0
      - ENABLE_CLAMAV=0
      - ENABLE_FAIL2BAN=0
      - ENABLE_AMAVIS=0
      - SSL_TYPE=letsencrypt # Tell docker-mailserver to use Let's Encrypt certificates
    cap_add:
      - NET_ADMIN
    deploy:
      replicas: ${PROD_REPLICAS}

  nginxprod:
    image: nginx:latest
    volumes:
      - ./nginx_prod.conf:/etc/nginx/nginx.conf
      - ./data/certbot/www:/var/www/certbot/:ro
      - ./data/certbot/conf/:/etc/nginx/ssl/:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - django
      - wordpress
    networks:
      - internal_network
    deploy:
      replicas: ${PROD_REPLICAS}

  nginxdev:
    image: nginx:latest
    volumes:
      - ./nginx_dev.conf:/etc/nginx/nginx.conf
      - ./data/certbot/conf/:/etc/nginx/ssl/:ro
    ports:
      - "8000:8000"
    depends_on:
      - django
    networks:
      - internal_network
    deploy:
      replicas: ${DEV_REPLICAS}
      
networks:
  internal_network:
      driver: bridge