version: '3.9'

services:

  db:
    image: postgres:13
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - internal_network

  django:
    build: ./lycaste
    volumes:
      - ./data/img:/app/main/static/img
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=db
    depends_on:
      - db
    networks:
      - internal_network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # for website config
      - /etc/letsencrypt:/etc/letsencrypt         # for ssl keys
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - django
    networks:
      - internal_network

  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    hostname: mail.lycaste.eu
    ports:
      - "25:25"     # SMTP
      - "465:465"   # SMTPS (SSL)
      - "587:587"   # Submission (STARTTLS)
      - "993:993"   # IMAPS (SSL)
    volumes:
      - ./data/mailserver/mail-data/:/var/mail/
      - ./data/mailserver/mail-state/:/var/mail-state/
      - ./data/mailserver/mail-logs/:/var/log/mail/
      - ./data/mailserver/config/:/tmp/docker-mailserver/
      - /etc/letsencrypt/:/etc/letsencrypt:ro
    environment:
      - ENABLE_SPAMASSASSIN=1
      - ENABLE_CLAMAV=1
      - ENABLE_FAIL2BAN=1
      - SSL_TYPE=letsencrypt # Tell docker-mailserver to use Let's Encrypt certificates
    cap_add:
      - NET_ADMIN

networks:
  internal_network:
      driver: bridge